language: c
sudo: required
cache: apt
os:
  - linux
services:
  - docker

env:
  - TAG=centos7_ocaml4.06.0 OS=centos:7 ALIAS='centos_ocaml4.06.0'
  - TAG=centos7_ocaml4.05.0 OS=centos:7 ALIAS='centos_ocaml4.05.0'
  - TAG=centos7_ocaml4.04.1 OS=centos:7 ALIAS='centos_ocaml4.04.1'
  - TAG=centos7_ocaml4.03.0 OS=centos:7 ALIAS='centos_ocaml4.03.0'
  - TAG=debian8_ocaml4.06.0 OS=debian:8 ALIAS='debian_ocaml4.06.0 4.06.0'
  - TAG=debian8_ocaml4.05.0 OS=debian:8 ALIAS='debian_ocaml4.05.0 4.05.0'
  - TAG=debian8_ocaml4.04.1 OS=debian:8 ALIAS='debian_ocaml4.04.1 4.04.1 latest'
  - TAG=debian8_ocaml4.03.0 OS=debian:8 ALIAS='debian_ocaml4.03.0 4.03.0'
matrix:
  allow_failures:
    - env: TAG=centos7_ocaml4.06.0 OS=centos:7 ALIAS='centos_ocaml4.06.0'
    - env: TAG=debian8_ocaml4.06.0 OS=debian:8 ALIAS='debian_ocaml4.06.0 4.06.0'

install:
  - sudo apt-get update
  - sudo apt-get install -y -q -o Dpkg::Options::="--force-confnew" docker-engine

before_script:
  - docker run -d --name mariadb -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mariadb:10.2
  - docker run -d --name postgres postgres:alpine

script:
  - bash -eu travis-ci.sh
