os:
  - linux
env:
  matrix:
    - TAG=latest OS=alpine
    - TAG=alpine3.5_ocaml4.05.0 OS=alpine
    - TAG=alpine3.5_ocaml4.04.1 OS=alpine
    - TAG=alpine3.5_ocaml4.03.0 OS=alpine

language: c
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - ./generate.sh > Dockerfile
  - docker build -t akabe/iocaml-datascience:$TAG .

script:
  - ./test/run_test.sh akabe/iocaml-datascience:$TAG

after_success:
  - |-
    if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PWD
      docker push akabe/iocaml-datascience:$TAG
    else
      echo -e "\033[33mSkip deploying image to DockerHub...\033[0m"
    fi
